/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Toolkit;

/**
 *
 * @author timon
 */
public class conversor extends javax.swing.JFrame {

    /**
     * Creates new form conversor
     */
    public conversor() {
        initComponents();
        setIcon();
        this.setLocationRelativeTo(null);
    }
    public void setIcon(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/iconBT.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JTextFieldToKelvin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        toKelvin = new javax.swing.JButton();
        toCelciusLabel = new javax.swing.JLabel();
        JTextFieldToCelcius = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        toCelcius = new javax.swing.JButton();
        toKelvinLabel = new javax.swing.JLabel();
        goBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(780, 450));
        setMinimumSize(new java.awt.Dimension(780, 450));
        getContentPane().setLayout(null);

        JTextFieldToKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldToKelvinActionPerformed(evt);
            }
        });
        getContentPane().add(JTextFieldToKelvin);
        JTextFieldToKelvin.setBounds(137, 234, 114, 26);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Celcius a Kelvin");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(97, 197, 104, 17);

        toKelvin.setText("Pasar a Kelvin!");
        toKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toKelvinActionPerformed(evt);
            }
        });
        getContentPane().add(toKelvin);
        toKelvin.setBounds(303, 233, 170, 29);

        toCelciusLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(toCelciusLabel);
        toCelciusLabel.setBounds(520, 110, 120, 29);

        JTextFieldToCelcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldToCelciusActionPerformed(evt);
            }
        });
        getContentPane().add(JTextFieldToCelcius);
        JTextFieldToCelcius.setBounds(140, 113, 114, 26);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Kelvin a Celcius");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(95, 74, 104, 17);

        toCelcius.setText("Pasar a Celcius!");
        toCelcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCelciusActionPerformed(evt);
            }
        });
        getContentPane().add(toCelcius);
        toCelcius.setBounds(310, 110, 170, 29);

        toKelvinLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(toKelvinLabel);
        toKelvinLabel.setBounds(530, 233, 118, 29);

        goBack.setText("Volver");
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });
        getContentPane().add(goBack);
        goBack.setBounds(353, 331, 77, 29);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Webp.net-resizeimage.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 770, 400);

        setBounds(0, 0, 786, 453);
    }// </editor-fold>//GEN-END:initComponents

    private void JTextFieldToKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldToKelvinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldToKelvinActionPerformed

    private void toKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toKelvinActionPerformed
        if(isNumeric(JTextFieldToKelvin.getText())){
            toKelvinLabel.setText(celciusToKelvin(JTextFieldToKelvin.getText()));
        }
    }//GEN-LAST:event_toKelvinActionPerformed

    private void JTextFieldToCelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldToCelciusActionPerformed
        
    }//GEN-LAST:event_JTextFieldToCelciusActionPerformed

    private void toCelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toCelciusActionPerformed
        if(isNumeric(JTextFieldToCelcius.getText())){
            toCelciusLabel.setText(kelvinToCelcius(JTextFieldToCelcius.getText()));
        }
    }//GEN-LAST:event_toCelciusActionPerformed

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
        main ventanaprincipal = new main();
        ventanaprincipal.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_goBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextFieldToCelcius;
    private javax.swing.JTextField JTextFieldToKelvin;
    private javax.swing.JButton goBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton toCelcius;
    private javax.swing.JLabel toCelciusLabel;
    private javax.swing.JButton toKelvin;
    private javax.swing.JLabel toKelvinLabel;
    // End of variables declaration//GEN-END:variables


public static boolean isNumeric(String str)  
{  
  try  
  {  
    Double.parseDouble(str);  
  }  
  catch(NumberFormatException nfe)  
  {  
    return false;  
  }  
  return true;  
}

    private static String celciusToKelvin(java.lang.String temp) {
        service.Converter_Service service = new service.Converter_Service();
        service.Converter port = service.getConverterPort();
        return port.celciusToKelvin(temp);
    }

    private static String kelvinToCelcius(java.lang.String temp) {
        service.Converter_Service service = new service.Converter_Service();
        service.Converter port = service.getConverterPort();
        return port.kelvinToCelcius(temp);
    }



}
